# Generated by Django 5.2.1 on 2025-06-15 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Hashrates",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("hashrate", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "algorithm",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="device_algorithms",
                        to="core.algorithm",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="device_algorithms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="device_algorithms",
                        to="core.device",
                    ),
                ),
            ],
            options={
                "verbose_name": "Хэшрейты",
                "verbose_name_plural": "Хэшрейты",
            },
        ),
    ]
