# Generated by Django 5.2.1 on 2025-06-15 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_cryptocurrency_algorithm"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mining",
            name="algorithm",
        ),
        migrations.AddField(
            model_name="mining",
            name="exchange",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mining_sessions",
                to="core.exchange",
            ),
        ),
    ]
