# Generated by Django 5.2.1 on 2025-06-15 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_remove_mining_algorithm_mining_exchange"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mining",
            name="hashrate",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
