# Generated by Django 5.2.1 on 2025-06-19 10:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_mining_hashrate"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hashrates",
            options={"verbose_name": "Хешрейты", "verbose_name_plural": "Хешрейты"},
        ),
        migrations.RemoveField(
            model_name="mining",
            name="hashrate",
        ),
    ]
