# Generated by Django 5.2.1 on 2025-06-19 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_alter_hashrates_options_remove_mining_hashrate"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="algorithm",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="algorithms",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="cryptocurrencyprice",
            name="cryptocurrency",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prices",
                to="core.cryptocurrency",
            ),
        ),
        migrations.AlterField(
            model_name="cryptocurrencyprice",
            name="exchange",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prices",
                to="core.exchange",
            ),
        ),
        migrations.AlterField(
            model_name="hashrates",
            name="algorithm",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="device_algorithms",
                to="core.algorithm",
            ),
        ),
        migrations.AlterField(
            model_name="hashrates",
            name="device",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="device_algorithms",
                to="core.device",
            ),
        ),
        migrations.AlterField(
            model_name="mining",
            name="cryptocurrency",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mining_sessions",
                to="core.cryptocurrency",
            ),
        ),
        migrations.AlterField(
            model_name="mining",
            name="device",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mining_sessions",
                to="core.device",
            ),
        ),
        migrations.AlterField(
            model_name="mining",
            name="exchange",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mining_sessions",
                to="core.exchange",
            ),
        ),
    ]
